services:
  - type: web
    name: mamaai-backend
    runtime: python
    rootDir: mama/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: OPEN_ROUTER_API_KEY
        sync: false
      - key: OPEN_ROUTER_MODEL
        value: openai/gpt-oss-120b:free
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
