import { useState, useEffect } from 'react';
import { FileText, Download, Share2, Activity, HeartPulse, Droplet, Loader2, Sparkles, CheckCircle } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import ReactMarkdown from 'react-markdown';
import { collection, getDocs, orderBy, query, limit } from 'firebase/firestore';
import { db } from '../firebase';
import { useAuth } from '../context/AuthContext';

const Reports = () => {
  const { user, userProfile } = useAuth();
  const [summary, setSummary] = useState({ eyelid: null, meals: 0, kicks: null, symptoms: 0 });
  const [generatingReport, setGeneratingReport] = useState(false);
  const [sendingToAsha, setSendingToAsha] = useState(false);
  const [sendStatus, setSendStatus] = useState('');
  const [reportText, setReportText] = useState('');
  const [error, setError] = useState('');

  const hbData = [
    { week: 'Wk 26', hb: 9.8 },
    { week: 'Wk 28', hb: 10.1 },
    { week: 'Wk 30', hb: 10.4 },
    { week: 'Wk 32', hb: 11.2 },
  ];

  useEffect(() => {
    if (!user) return;
    const base = (sub) => collection(db, 'users', user.uid, 'reports', sub, 'entries');
    const load = async () => {
      const [eyelidSnap, mealSnap, kickSnap, symptomSnap] = await Promise.all([
        getDocs(query(base('eyelid_scans'), orderBy('savedAt', 'desc'), limit(1))),
        getDocs(base('meal_scans')),
        getDocs(query(base('kick_sessions'), orderBy('savedAt', 'desc'), limit(1))),
        getDocs(base('symptom_chats')),
      ]);
      setSummary({
        eyelid: eyelidSnap.empty ? null : eyelidSnap.docs[0].data(),
        meals: mealSnap.size,
        kicks: kickSnap.empty ? null : kickSnap.docs[0].data(),
        symptoms: symptomSnap.size,
      });
    };
    load();
  }, [user]);

  const buildHtml = (text) => {
    const htmlContent = text
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1 style="color:#9D4EDD">$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>[\s\S]*?<\/li>)/g, '<ul>$1</ul>')
      .replace(/\n{2,}/g, '</p><p>')
      .trim();

    return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>MamaAI Doctor Report</title>
    <style>
      body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;color:#1a1a2e;line-height:1.8;padding:0 20px}
      h1{color:#9D4EDD;border-bottom:2px solid #FF4FA3;padding-bottom:10px;margin-top:0}
      h2{color:#9D4EDD;margin-top:28px;margin-bottom:8px}
      h3{color:#333;margin-top:20px;margin-bottom:6px}
      p{margin:8px 0;color:#333}
      ul{padding-left:20px;margin:8px 0}
      li{margin:4px 0;color:#333}
      strong{color:#1a1a2e}
      .meta{color:#666;font-size:13px;margin-bottom:20px}
      .footer{margin-top:40px;font-size:12px;color:#888;border-top:1px solid #eee;padding-top:12px}
      @media print{body{margin:20px}}
    </style>
  </head>
  <body>
    <h1>MamaAI — Doctor Summary Report</h1>
    <p class="meta"><strong>Patient:</strong> ${userProfile?.name ?? 'Mother'} &nbsp;|&nbsp; <strong>Generated:</strong> ${new Date().toLocaleString()}</p>
    <hr/>
    <div><p>${htmlContent}</p></div>
    <div class="footer">Generated by MamaAI &middot; For clinical use only &middot; Not a substitute for professional medical advice</div>
    <script>window.onload=()=>window.print();<\/script>
  </body>
</html>`;
  };

  const handleGenerateReport = async () => {
    if (!user) return;
    setGeneratingReport(true);
    setError('');
    setReportText('');
    setSendStatus('');
    try {
      const base = (sub) => collection(db, 'users', user.uid, 'reports', sub, 'entries');
      const [eyelidSnap, mealSnap, kickSnap, symptomSnap] = await Promise.all([
        getDocs(query(base('eyelid_scans'), orderBy('savedAt', 'desc'), limit(1))),
        getDocs(query(base('meal_scans'), orderBy('savedAt', 'desc'), limit(3))),
        getDocs(query(base('kick_sessions'), orderBy('savedAt', 'desc'), limit(1))),
        getDocs(query(base('symptom_chats'), orderBy('savedAt', 'desc'), limit(1))),
      ]);
      const reportPayload = {
        eyelid: eyelidSnap.empty ? null : eyelidSnap.docs[0].data(),
        meals: mealSnap.docs.map(d => d.data()),
        kicks: kickSnap.empty ? null : kickSnap.docs[0].data(),
        symptoms: symptomSnap.empty ? [] : (symptomSnap.docs[0].data().messages ?? []),
      };
      const res = await fetch('http://localhost:5000/api/report/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(reportPayload),
      });
      const data = await res.json();
      if (data.success) setReportText(data.report);
      else setError(data.error || 'Failed to generate report');
    } catch {
      setError('Could not connect to server. Please ensure the backend is running.');
    } finally {
      setGeneratingReport(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!reportText) return;
    const blob = new Blob([buildHtml(reportText)], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MamaAI_Report_${new Date().toISOString().slice(0, 10)}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSendToAsha = async () => {
    if (!reportText) {
      setError('Please generate the report first before sending.');
      return;
    }
    setSendingToAsha(true);
    setSendStatus('');
    setError('');
    try {
      const res = await fetch('http://localhost:5000/api/report/send-to-asha', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          htmlContent: buildHtml(reportText),
          motherName: userProfile?.name ?? 'Mother',
        }),
      });
      const data = await res.json();
      if (data.success) {
        setSendStatus(data.message);
        setTimeout(() => setSendStatus(''), 4000);
      } else {
        setError(data.error || 'Failed to send report');
      }
    } catch {
      setError('Could not connect to server.');
    } finally {
      setSendingToAsha(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white flex items-center gap-3 mb-2">
            <FileText className="text-accentPink w-8 h-8"/> My Health Reports
          </h1>
          <p className="text-textSecondary">Comprehensive view of your pregnancy journey.</p>
        </div>
        <div className="flex gap-3 flex-wrap">
          <button
            onClick={handleGenerateReport}
            disabled={generatingReport}
            className="px-6 py-2 rounded-xl bg-gradient-to-r from-accentPink to-secondaryPurple font-medium transition-colors flex items-center gap-2 text-white hover:shadow-[0_0_15px_rgba(255,79,163,0.4)] disabled:opacity-60"
          >
            {generatingReport
              ? <><Loader2 className="w-4 h-4 animate-spin"/> Generating...</>
              : <><Sparkles className="w-4 h-4"/> Generate Doctor Report</>}
          </button>
          <button
            onClick={handleDownloadPDF}
            disabled={!reportText}
            className="px-6 py-2 rounded-xl bg-white/5 hover:bg-white/10 font-medium transition-colors flex items-center gap-2 text-white disabled:opacity-40"
          >
            <Download className="w-4 h-4"/> Download PDF
          </button>
          <button
            onClick={handleSendToAsha}
            disabled={sendingToAsha || !reportText}
            className="px-6 py-2 rounded-xl bg-white/5 hover:bg-white/10 font-medium transition-colors flex items-center gap-2 text-white disabled:opacity-40"
          >
            {sendingToAsha
              ? <><Loader2 className="w-4 h-4 animate-spin"/> Sending...</>
              : sendStatus
              ? <><CheckCircle className="w-4 h-4 text-successGreen"/> {sendStatus}</>
              : <><Share2 className="w-4 h-4"/> Send to ASHA and Doctors</>}
          </button>
        </div>
      </div>

      {error && (
        <div className="p-4 rounded-xl bg-dangerRed/10 border border-dangerRed text-dangerRed text-sm">{error}</div>
      )}

      {reportText && (
        <div className="glass p-8 rounded-3xl border-t-4 border-accentPink">
          <h3 className="text-xl font-bold mb-4 text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-accentPink"/> AI-Generated Doctor Summary
          </h3>
          <div className="prose prose-invert prose-sm max-w-none
            prose-headings:text-white prose-headings:font-bold prose-headings:mt-4 prose-headings:mb-2
            prose-h1:text-xl prose-h2:text-lg prose-h3:text-base
            prose-p:text-textSecondary prose-p:leading-relaxed prose-p:my-1
            prose-li:text-textSecondary prose-li:my-0.5
            prose-ul:my-2 prose-ol:my-2
            prose-strong:text-white prose-strong:font-semibold
            prose-hr:border-white/10">
            <ReactMarkdown>{reportText}</ReactMarkdown>
          </div>
        </div>
      )}

      <div className="grid md:grid-cols-3 gap-6">
        <div className="glass p-6 rounded-3xl border-t-4 border-successGreen">
          <div className="flex items-center gap-3 mb-4">
            <HeartPulse className="w-6 h-6 text-successGreen" />
            <h3 className="font-semibold text-lg text-white">General Health</h3>
          </div>
          <div className="space-y-4">
            <div className="flex justify-between items-center border-b border-white/5 pb-2">
              <span className="text-textSecondary text-sm">Blood Pressure</span>
              <span className="text-white font-medium">110/70 <span className="text-xs text-successGreen ml-1">Normal</span></span>
            </div>
            <div className="flex justify-between items-center border-b border-white/5 pb-2">
              <span className="text-textSecondary text-sm">Symptom Chats</span>
              <span className="text-white font-medium">{summary.symptoms} <span className="text-xs text-successGreen ml-1">Saved</span></span>
            </div>
          </div>
        </div>

        <div className="glass p-6 rounded-3xl border-t-4 border-cyanAccent">
          <div className="flex items-center gap-3 mb-4">
            <Droplet className="w-6 h-6 text-cyanAccent" />
            <h3 className="font-semibold text-lg text-white">Nutrition & Iron</h3>
          </div>
          <div className="space-y-4">
            <div className="flex justify-between items-center border-b border-white/5 pb-2">
              <span className="text-textSecondary text-sm">Hemoglobin (AI)</span>
              <span className="text-white font-medium">
                {summary.eyelid?.hb ?? '—'} {summary.eyelid ? 'g/dL' : ''}
                <span className="text-xs text-successGreen ml-1">{summary.eyelid?.risk ?? 'No scan saved'}</span>
              </span>
            </div>
            <div className="flex justify-between items-center border-b border-white/5 pb-2">
              <span className="text-textSecondary text-sm">Meals Logged</span>
              <span className="text-white font-medium">{summary.meals} <span className="text-xs text-successGreen ml-1">Scanned</span></span>
            </div>
          </div>
        </div>

        <div className="glass p-6 rounded-3xl border-t-4 border-secondaryPurple">
          <div className="flex items-center gap-3 mb-4">
            <Activity className="w-6 h-6 text-secondaryPurple" />
            <h3 className="font-semibold text-lg text-white">Fetal Activity</h3>
          </div>
          <div className="space-y-4">
            <div className="flex justify-between items-center border-b border-white/5 pb-2">
              <span className="text-textSecondary text-sm">Avg Kicks/Day</span>
              <span className="text-white font-medium">
                {summary.kicks?.weekly_avg ?? '—'} <span className="text-xs text-successGreen ml-1">{summary.kicks ? 'Active' : 'No data'}</span>
              </span>
            </div>
            <div className="flex justify-between items-center border-b border-white/5 pb-2">
              <span className="text-textSecondary text-sm">Last Session</span>
              <span className="text-white font-medium">
                {summary.kicks?.today ?? '—'} <span className="text-xs text-successGreen ml-1">{summary.kicks ? 'kicks' : ''}</span>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className="glass p-8 rounded-3xl">
        <h3 className="text-xl font-bold mb-6 text-white">Hemoglobin Trend (Last 8 Weeks)</h3>
        <div className="h-[300px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={hbData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <defs>
                <linearGradient id="colorHb" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#00D9FF" stopOpacity={0.3}/>
                  <stop offset="95%" stopColor="#00D9FF" stopOpacity={0}/>
                </linearGradient>
              </defs>
              <XAxis dataKey="week" stroke="#CBD5E1" fontSize={12} tickLine={false} axisLine={false} />
              <YAxis stroke="#CBD5E1" fontSize={12} tickLine={false} axisLine={false} domain={[8, 14]} />
              <Tooltip contentStyle={{ backgroundColor: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: '12px', color: 'var(--text-1)' }} />
              <Area type="monotone" dataKey="hb" stroke="#00D9FF" strokeWidth={3} fillOpacity={1} fill="url(#colorHb)" />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
};

export default Reports;
